export default {
  login: 'salatech',
  id: 42133389,
  node_id: 'MDQ6VXNlcjQyMTMzMzg5',
  avatar_url: 'https://avatars3.githubusercontent.com/u/42133389?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/salatech',
  html_url: 'https://github.com/salatech',
  followers_url: 'https://api.github.com/users/salatech/followers',
  following_url:
    'https://api.github.com/users/salatech/following{/other_user}',
  gists_url: 'https://api.github.com/users/salatech/gists{/gist_id}',
  starred_url:
    'https://api.github.com/users/salatech/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/salatech/subscriptions',
  organizations_url: 'https://api.github.com/users/salatech/orgs',
  repos_url: 'https://api.github.com/users/salatech/repos',
  events_url: 'https://api.github.com/users/salatech/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/salatech/received_events',
  type: 'User',
  site_admin: false,
  name: 'solahudeen abdulrahmon',
  company: 'salatech',
  blog: '',
  location: 'Nigeria',
  email: null,
  hireable: null,
  bio: 'Frontend developer',
  twitter_username: 'salatech2',
  public_repos: 20,
  public_gists: 0,
  followers: 5,
  following: 2,
  created_at: '',
  updated_at: '',
};
